// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Channel_P.proto

#define PROTOBUF_USE_DLLS
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Channel_P.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Channel_P {
class channel_chattingDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<channel_chatting> {
} _channel_chatting_default_instance_;

namespace protobuf_Channel_5fP_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(channel_chatting, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(channel_chatting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(channel_chatting, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(channel_chatting, target_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(channel_chatting, message_),
  1,
  2,
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(channel_chatting)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_channel_chatting_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Channel_P.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _channel_chatting_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _channel_chatting_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\017Channel_P.proto\022\tChannel_P\"\?\n\020channel_"
      "chatting\022\n\n\002id\030\001 \002(\005\022\016\n\006target\030\002 \002(\005\022\017\n\007"
      "message\030\003 \002(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 93);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Channel_P.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_Channel_5fP_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int channel_chatting::kIdFieldNumber;
const int channel_chatting::kTargetFieldNumber;
const int channel_chatting::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

channel_chatting::channel_chatting()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Channel_5fP_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Channel_P.channel_chatting)
}
channel_chatting::channel_chatting(const channel_chatting& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_message()) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&id_, &from.id_,
    reinterpret_cast<char*>(&target_) -
    reinterpret_cast<char*>(&id_) + sizeof(target_));
  // @@protoc_insertion_point(copy_constructor:Channel_P.channel_chatting)
}

void channel_chatting::SharedCtor() {
  _cached_size_ = 0;
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, reinterpret_cast<char*>(&target_) -
    reinterpret_cast<char*>(&id_) + sizeof(target_));
}

channel_chatting::~channel_chatting() {
  // @@protoc_insertion_point(destructor:Channel_P.channel_chatting)
  SharedDtor();
}

void channel_chatting::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void channel_chatting::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* channel_chatting::descriptor() {
  protobuf_Channel_5fP_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Channel_5fP_2eproto::file_level_metadata[0].descriptor;
}

const channel_chatting& channel_chatting::default_instance() {
  protobuf_Channel_5fP_2eproto::InitDefaults();
  return *internal_default_instance();
}

channel_chatting* channel_chatting::New(::google::protobuf::Arena* arena) const {
  channel_chatting* n = new channel_chatting;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void channel_chatting::Clear() {
// @@protoc_insertion_point(message_clear_start:Channel_P.channel_chatting)
  if (has_message()) {
    GOOGLE_DCHECK(!message_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*message_.UnsafeRawStringPointer())->clear();
  }
  if (_has_bits_[0 / 32] & 6u) {
    ::memset(&id_, 0, reinterpret_cast<char*>(&target_) -
      reinterpret_cast<char*>(&id_) + sizeof(target_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool channel_chatting::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Channel_P.channel_chatting)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8u) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 target = 2;
      case 2: {
        if (tag == 16u) {
          set_has_target();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &target_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string message = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Channel_P.channel_chatting.message");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Channel_P.channel_chatting)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Channel_P.channel_chatting)
  return false;
#undef DO_
}

void channel_chatting::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Channel_P.channel_chatting)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required int32 target = 2;
  if (has_target()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->target(), output);
  }

  // required string message = 3;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Channel_P.channel_chatting.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->message(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Channel_P.channel_chatting)
}

::google::protobuf::uint8* channel_chatting::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Channel_P.channel_chatting)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required int32 target = 2;
  if (has_target()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->target(), target);
  }

  // required string message = 3;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Channel_P.channel_chatting.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->message(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Channel_P.channel_chatting)
  return target;
}

size_t channel_chatting::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Channel_P.channel_chatting)
  size_t total_size = 0;

  if (has_message()) {
    // required string message = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  if (has_id()) {
    // required int32 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  if (has_target()) {
    // required int32 target = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->target());
  }

  return total_size;
}
size_t channel_chatting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Channel_P.channel_chatting)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string message = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());

    // required int32 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());

    // required int32 target = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->target());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void channel_chatting::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Channel_P.channel_chatting)
  GOOGLE_DCHECK_NE(&from, this);
  const channel_chatting* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const channel_chatting>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Channel_P.channel_chatting)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Channel_P.channel_chatting)
    MergeFrom(*source);
  }
}

void channel_chatting::MergeFrom(const channel_chatting& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Channel_P.channel_chatting)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 7u) {
    if (from.has_message()) {
      set_has_message();
      message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_target()) {
      set_target(from.target());
    }
  }
}

void channel_chatting::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Channel_P.channel_chatting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void channel_chatting::CopyFrom(const channel_chatting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Channel_P.channel_chatting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool channel_chatting::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void channel_chatting::Swap(channel_chatting* other) {
  if (other == this) return;
  InternalSwap(other);
}
void channel_chatting::InternalSwap(channel_chatting* other) {
  message_.Swap(&other->message_);
  std::swap(id_, other->id_);
  std::swap(target_, other->target_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata channel_chatting::GetMetadata() const {
  protobuf_Channel_5fP_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Channel_5fP_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// channel_chatting

// required int32 id = 1;
bool channel_chatting::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void channel_chatting::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
void channel_chatting::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void channel_chatting::clear_id() {
  id_ = 0;
  clear_has_id();
}
::google::protobuf::int32 channel_chatting::id() const {
  // @@protoc_insertion_point(field_get:Channel_P.channel_chatting.id)
  return id_;
}
void channel_chatting::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Channel_P.channel_chatting.id)
}

// required int32 target = 2;
bool channel_chatting::has_target() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void channel_chatting::set_has_target() {
  _has_bits_[0] |= 0x00000004u;
}
void channel_chatting::clear_has_target() {
  _has_bits_[0] &= ~0x00000004u;
}
void channel_chatting::clear_target() {
  target_ = 0;
  clear_has_target();
}
::google::protobuf::int32 channel_chatting::target() const {
  // @@protoc_insertion_point(field_get:Channel_P.channel_chatting.target)
  return target_;
}
void channel_chatting::set_target(::google::protobuf::int32 value) {
  set_has_target();
  target_ = value;
  // @@protoc_insertion_point(field_set:Channel_P.channel_chatting.target)
}

// required string message = 3;
bool channel_chatting::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void channel_chatting::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
void channel_chatting::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
void channel_chatting::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message();
}
const ::std::string& channel_chatting::message() const {
  // @@protoc_insertion_point(field_get:Channel_P.channel_chatting.message)
  return message_.GetNoArena();
}
void channel_chatting::set_message(const ::std::string& value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Channel_P.channel_chatting.message)
}
#if LANG_CXX11
void channel_chatting::set_message(::std::string&& value) {
  set_has_message();
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Channel_P.channel_chatting.message)
}
#endif
void channel_chatting::set_message(const char* value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Channel_P.channel_chatting.message)
}
void channel_chatting::set_message(const char* value, size_t size) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Channel_P.channel_chatting.message)
}
::std::string* channel_chatting::mutable_message() {
  set_has_message();
  // @@protoc_insertion_point(field_mutable:Channel_P.channel_chatting.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* channel_chatting::release_message() {
  // @@protoc_insertion_point(field_release:Channel_P.channel_chatting.message)
  clear_has_message();
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void channel_chatting::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    set_has_message();
  } else {
    clear_has_message();
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Channel_P.channel_chatting.message)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Channel_P

// @@protoc_insertion_point(global_scope)
